[package]
name = "lean5-elab"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Lean5 elaborator - type inference and tactics"

[dependencies]
lean5-kernel.workspace = true
lean5-parser.workspace = true
lean5-macro.workspace = true
lean5-auto.workspace = true
thiserror.workspace = true
hashbrown.workspace = true

[dev-dependencies]
proptest.workspace = true
